//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.06 at 12:41:56 PM PDT 
//


package org.uniprot.uniprot;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Describes different types of general annotations.
 *             Equivalent to the flat file CC-line.
 * 
 * <p>Java class for commentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="commentType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="molecule" type="{http://uniprot.org/uniprot}moleculeType" minOccurs="0"/&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;group ref="{http://uniprot.org/uniprot}bpcCommentGroup"/&gt;
 *           &lt;sequence&gt;
 *             &lt;element name="reaction" type="{http://uniprot.org/uniprot}reactionType"/&gt;
 *             &lt;element name="physiologicalReaction" type="{http://uniprot.org/uniprot}physiologicalReactionType" maxOccurs="2" minOccurs="0"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;sequence&gt;
 *             &lt;element name="cofactor" type="{http://uniprot.org/uniprot}cofactorType" maxOccurs="unbounded"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;sequence&gt;
 *             &lt;element name="subcellularLocation" type="{http://uniprot.org/uniprot}subcellularLocationType" maxOccurs="unbounded"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;element name="conflict"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="sequence" minOccurs="0"&gt;
 *                       &lt;complexType&gt;
 *                         &lt;complexContent&gt;
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                             &lt;attribute name="resource" use="required"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                   &lt;enumeration value="EMBL-CDS"/&gt;
 *                                   &lt;enumeration value="EMBL"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/attribute&gt;
 *                             &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                             &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;/restriction&gt;
 *                         &lt;/complexContent&gt;
 *                       &lt;/complexType&gt;
 *                     &lt;/element&gt;
 *                   &lt;/sequence&gt;
 *                   &lt;attribute name="type" use="required"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="frameshift"/&gt;
 *                         &lt;enumeration value="erroneous initiation"/&gt;
 *                         &lt;enumeration value="erroneous termination"/&gt;
 *                         &lt;enumeration value="erroneous gene model prediction"/&gt;
 *                         &lt;enumeration value="erroneous translation"/&gt;
 *                         &lt;enumeration value="miscellaneous discrepancy"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/attribute&gt;
 *                   &lt;attribute name="ref" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *           &lt;sequence&gt;
 *             &lt;element name="link" maxOccurs="unbounded" minOccurs="0"&gt;
 *               &lt;complexType&gt;
 *                 &lt;complexContent&gt;
 *                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                     &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *                   &lt;/restriction&gt;
 *                 &lt;/complexContent&gt;
 *               &lt;/complexType&gt;
 *             &lt;/element&gt;
 *           &lt;/sequence&gt;
 *           &lt;sequence&gt;
 *             &lt;element name="event" type="{http://uniprot.org/uniprot}eventType" maxOccurs="4"/&gt;
 *             &lt;element name="isoform" type="{http://uniprot.org/uniprot}isoformType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;sequence&gt;
 *             &lt;element name="interactant" type="{http://uniprot.org/uniprot}interactantType" maxOccurs="2" minOccurs="2"/&gt;
 *             &lt;element name="organismsDiffer" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *             &lt;element name="experiments" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;element name="disease"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                     &lt;element name="acronym" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                     &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                     &lt;element name="dbReference" type="{http://uniprot.org/uniprot}dbReferenceType"/&gt;
 *                   &lt;/sequence&gt;
 *                   &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="location" type="{http://uniprot.org/uniprot}locationType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="text" type="{http://uniprot.org/uniprot}evidencedStringType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="type" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="allergen"/&gt;
 *             &lt;enumeration value="alternative products"/&gt;
 *             &lt;enumeration value="biotechnology"/&gt;
 *             &lt;enumeration value="biophysicochemical properties"/&gt;
 *             &lt;enumeration value="catalytic activity"/&gt;
 *             &lt;enumeration value="caution"/&gt;
 *             &lt;enumeration value="cofactor"/&gt;
 *             &lt;enumeration value="developmental stage"/&gt;
 *             &lt;enumeration value="disease"/&gt;
 *             &lt;enumeration value="domain"/&gt;
 *             &lt;enumeration value="disruption phenotype"/&gt;
 *             &lt;enumeration value="activity regulation"/&gt;
 *             &lt;enumeration value="function"/&gt;
 *             &lt;enumeration value="induction"/&gt;
 *             &lt;enumeration value="miscellaneous"/&gt;
 *             &lt;enumeration value="pathway"/&gt;
 *             &lt;enumeration value="pharmaceutical"/&gt;
 *             &lt;enumeration value="polymorphism"/&gt;
 *             &lt;enumeration value="PTM"/&gt;
 *             &lt;enumeration value="RNA editing"/&gt;
 *             &lt;enumeration value="similarity"/&gt;
 *             &lt;enumeration value="subcellular location"/&gt;
 *             &lt;enumeration value="sequence caution"/&gt;
 *             &lt;enumeration value="subunit"/&gt;
 *             &lt;enumeration value="tissue specificity"/&gt;
 *             &lt;enumeration value="toxic dose"/&gt;
 *             &lt;enumeration value="online information"/&gt;
 *             &lt;enumeration value="mass spectrometry"/&gt;
 *             &lt;enumeration value="interaction"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="locationType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="mass" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *       &lt;attribute name="error" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="method" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="evidence" type="{http://uniprot.org/uniprot}intListType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "commentType", propOrder = {
    "molecule",
    "disease",
    "interactants",
    "organismsDiffer",
    "experiments",
    "events",
    "isoforms",
    "links",
    "conflict",
    "subcellularLocations",
    "cofactors",
    "reaction",
    "physiologicalReactions",
    "absorption",
    "kinetics",
    "phDependence",
    "redoxPotential",
    "temperatureDependence",
    "locations",
    "texts"
})
public class CommentType
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    protected MoleculeType molecule;
    protected CommentType.Disease disease;
    @XmlElement(name = "interactant")
    protected List<InteractantType> interactants;
    @XmlElement(defaultValue = "false")
    protected Boolean organismsDiffer;
    protected Integer experiments;
    @XmlElement(name = "event")
    protected List<EventType> events;
    @XmlElement(name = "isoform")
    protected List<IsoformType> isoforms;
    @XmlElement(name = "link")
    protected List<CommentType.Link> links;
    protected CommentType.Conflict conflict;
    @XmlElement(name = "subcellularLocation")
    protected List<SubcellularLocationType> subcellularLocations;
    @XmlElement(name = "cofactor")
    protected List<CofactorType> cofactors;
    protected ReactionType reaction;
    @XmlElement(name = "physiologicalReaction")
    protected List<PhysiologicalReactionType> physiologicalReactions;
    protected CommentType.Absorption absorption;
    protected CommentType.Kinetics kinetics;
    protected CommentType.PhDependence phDependence;
    protected CommentType.RedoxPotential redoxPotential;
    protected CommentType.TemperatureDependence temperatureDependence;
    @XmlElement(name = "location")
    protected List<LocationType> locations;
    @XmlElement(name = "text")
    protected List<EvidencedStringType> texts;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "locationType")
    protected String locationType;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "mass")
    protected Float mass;
    @XmlAttribute(name = "error")
    protected String error;
    @XmlAttribute(name = "method")
    protected String method;
    @XmlAttribute(name = "evidence")
    protected List<Integer> evidences;

    /**
     * Gets the value of the molecule property.
     * 
     * @return
     *     possible object is
     *     {@link MoleculeType }
     *     
     */
    public MoleculeType getMolecule() {
        return molecule;
    }

    /**
     * Sets the value of the molecule property.
     * 
     * @param value
     *     allowed object is
     *     {@link MoleculeType }
     *     
     */
    public void setMolecule(MoleculeType value) {
        this.molecule = value;
    }

    /**
     * Gets the value of the disease property.
     * 
     * @return
     *     possible object is
     *     {@link CommentType.Disease }
     *     
     */
    public CommentType.Disease getDisease() {
        return disease;
    }

    /**
     * Sets the value of the disease property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommentType.Disease }
     *     
     */
    public void setDisease(CommentType.Disease value) {
        this.disease = value;
    }

    /**
     * Gets the value of the interactants property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interactants property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInteractants().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InteractantType }
     * 
     * 
     */
    public List<InteractantType> getInteractants() {
        if (interactants == null) {
            interactants = new ArrayList<InteractantType>();
        }
        return this.interactants;
    }

    /**
     * Gets the value of the organismsDiffer property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOrganismsDiffer() {
        return organismsDiffer;
    }

    /**
     * Sets the value of the organismsDiffer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOrganismsDiffer(Boolean value) {
        this.organismsDiffer = value;
    }

    /**
     * Gets the value of the experiments property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getExperiments() {
        return experiments;
    }

    /**
     * Sets the value of the experiments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setExperiments(Integer value) {
        this.experiments = value;
    }

    /**
     * Gets the value of the events property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the events property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEvents().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventType }
     * 
     * 
     */
    public List<EventType> getEvents() {
        if (events == null) {
            events = new ArrayList<EventType>();
        }
        return this.events;
    }

    /**
     * Gets the value of the isoforms property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the isoforms property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIsoforms().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IsoformType }
     * 
     * 
     */
    public List<IsoformType> getIsoforms() {
        if (isoforms == null) {
            isoforms = new ArrayList<IsoformType>();
        }
        return this.isoforms;
    }

    /**
     * Gets the value of the links property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the links property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommentType.Link }
     * 
     * 
     */
    public List<CommentType.Link> getLinks() {
        if (links == null) {
            links = new ArrayList<CommentType.Link>();
        }
        return this.links;
    }

    /**
     * Gets the value of the conflict property.
     * 
     * @return
     *     possible object is
     *     {@link CommentType.Conflict }
     *     
     */
    public CommentType.Conflict getConflict() {
        return conflict;
    }

    /**
     * Sets the value of the conflict property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommentType.Conflict }
     *     
     */
    public void setConflict(CommentType.Conflict value) {
        this.conflict = value;
    }

    /**
     * Gets the value of the subcellularLocations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subcellularLocations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubcellularLocations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubcellularLocationType }
     * 
     * 
     */
    public List<SubcellularLocationType> getSubcellularLocations() {
        if (subcellularLocations == null) {
            subcellularLocations = new ArrayList<SubcellularLocationType>();
        }
        return this.subcellularLocations;
    }

    /**
     * Gets the value of the cofactors property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cofactors property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCofactors().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CofactorType }
     * 
     * 
     */
    public List<CofactorType> getCofactors() {
        if (cofactors == null) {
            cofactors = new ArrayList<CofactorType>();
        }
        return this.cofactors;
    }

    /**
     * Gets the value of the reaction property.
     * 
     * @return
     *     possible object is
     *     {@link ReactionType }
     *     
     */
    public ReactionType getReaction() {
        return reaction;
    }

    /**
     * Sets the value of the reaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReactionType }
     *     
     */
    public void setReaction(ReactionType value) {
        this.reaction = value;
    }

    /**
     * Gets the value of the physiologicalReactions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the physiologicalReactions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhysiologicalReactions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhysiologicalReactionType }
     * 
     * 
     */
    public List<PhysiologicalReactionType> getPhysiologicalReactions() {
        if (physiologicalReactions == null) {
            physiologicalReactions = new ArrayList<PhysiologicalReactionType>();
        }
        return this.physiologicalReactions;
    }

    /**
     * Gets the value of the absorption property.
     * 
     * @return
     *     possible object is
     *     {@link CommentType.Absorption }
     *     
     */
    public CommentType.Absorption getAbsorption() {
        return absorption;
    }

    /**
     * Sets the value of the absorption property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommentType.Absorption }
     *     
     */
    public void setAbsorption(CommentType.Absorption value) {
        this.absorption = value;
    }

    /**
     * Gets the value of the kinetics property.
     * 
     * @return
     *     possible object is
     *     {@link CommentType.Kinetics }
     *     
     */
    public CommentType.Kinetics getKinetics() {
        return kinetics;
    }

    /**
     * Sets the value of the kinetics property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommentType.Kinetics }
     *     
     */
    public void setKinetics(CommentType.Kinetics value) {
        this.kinetics = value;
    }

    /**
     * Gets the value of the phDependence property.
     * 
     * @return
     *     possible object is
     *     {@link CommentType.PhDependence }
     *     
     */
    public CommentType.PhDependence getPhDependence() {
        return phDependence;
    }

    /**
     * Sets the value of the phDependence property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommentType.PhDependence }
     *     
     */
    public void setPhDependence(CommentType.PhDependence value) {
        this.phDependence = value;
    }

    /**
     * Gets the value of the redoxPotential property.
     * 
     * @return
     *     possible object is
     *     {@link CommentType.RedoxPotential }
     *     
     */
    public CommentType.RedoxPotential getRedoxPotential() {
        return redoxPotential;
    }

    /**
     * Sets the value of the redoxPotential property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommentType.RedoxPotential }
     *     
     */
    public void setRedoxPotential(CommentType.RedoxPotential value) {
        this.redoxPotential = value;
    }

    /**
     * Gets the value of the temperatureDependence property.
     * 
     * @return
     *     possible object is
     *     {@link CommentType.TemperatureDependence }
     *     
     */
    public CommentType.TemperatureDependence getTemperatureDependence() {
        return temperatureDependence;
    }

    /**
     * Sets the value of the temperatureDependence property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommentType.TemperatureDependence }
     *     
     */
    public void setTemperatureDependence(CommentType.TemperatureDependence value) {
        this.temperatureDependence = value;
    }

    /**
     * Gets the value of the locations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the locations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocationType }
     * 
     * 
     */
    public List<LocationType> getLocations() {
        if (locations == null) {
            locations = new ArrayList<LocationType>();
        }
        return this.locations;
    }

    /**
     * Gets the value of the texts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the texts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTexts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EvidencedStringType }
     * 
     * 
     */
    public List<EvidencedStringType> getTexts() {
        if (texts == null) {
            texts = new ArrayList<EvidencedStringType>();
        }
        return this.texts;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the locationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationType() {
        return locationType;
    }

    /**
     * Sets the value of the locationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationType(String value) {
        this.locationType = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the mass property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getMass() {
        return mass;
    }

    /**
     * Sets the value of the mass property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMass(Float value) {
        this.mass = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setError(String value) {
        this.error = value;
    }

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethod(String value) {
        this.method = value;
    }

    /**
     * Gets the value of the evidences property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the evidences property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEvidences().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getEvidences() {
        if (evidences == null) {
            evidences = new ArrayList<Integer>();
        }
        return this.evidences;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="max" type="{http://uniprot.org/uniprot}evidencedStringType" minOccurs="0"/&gt;
     *         &lt;element name="text" type="{http://uniprot.org/uniprot}evidencedStringType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "max",
        "texts"
    })
    public static class Absorption
        implements Serializable
    {

        private final static long serialVersionUID = -1L;
        protected EvidencedStringType max;
        @XmlElement(name = "text")
        protected List<EvidencedStringType> texts;

        /**
         * Gets the value of the max property.
         * 
         * @return
         *     possible object is
         *     {@link EvidencedStringType }
         *     
         */
        public EvidencedStringType getMax() {
            return max;
        }

        /**
         * Sets the value of the max property.
         * 
         * @param value
         *     allowed object is
         *     {@link EvidencedStringType }
         *     
         */
        public void setMax(EvidencedStringType value) {
            this.max = value;
        }

        /**
         * Gets the value of the texts property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the texts property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTexts().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EvidencedStringType }
         * 
         * 
         */
        public List<EvidencedStringType> getTexts() {
            if (texts == null) {
                texts = new ArrayList<EvidencedStringType>();
            }
            return this.texts;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="sequence" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="resource" use="required"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;enumeration value="EMBL-CDS"/&gt;
     *                       &lt;enumeration value="EMBL"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="type" use="required"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *             &lt;enumeration value="frameshift"/&gt;
     *             &lt;enumeration value="erroneous initiation"/&gt;
     *             &lt;enumeration value="erroneous termination"/&gt;
     *             &lt;enumeration value="erroneous gene model prediction"/&gt;
     *             &lt;enumeration value="erroneous translation"/&gt;
     *             &lt;enumeration value="miscellaneous discrepancy"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="ref" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sequence"
    })
    public static class Conflict
        implements Serializable
    {

        private final static long serialVersionUID = -1L;
        protected CommentType.Conflict.Sequence sequence;
        @XmlAttribute(name = "type", required = true)
        protected String type;
        @XmlAttribute(name = "ref")
        protected String ref;

        /**
         * Gets the value of the sequence property.
         * 
         * @return
         *     possible object is
         *     {@link CommentType.Conflict.Sequence }
         *     
         */
        public CommentType.Conflict.Sequence getSequence() {
            return sequence;
        }

        /**
         * Sets the value of the sequence property.
         * 
         * @param value
         *     allowed object is
         *     {@link CommentType.Conflict.Sequence }
         *     
         */
        public void setSequence(CommentType.Conflict.Sequence value) {
            this.sequence = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the ref property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRef() {
            return ref;
        }

        /**
         * Sets the value of the ref property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRef(String value) {
            this.ref = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="resource" use="required"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;enumeration value="EMBL-CDS"/&gt;
         *             &lt;enumeration value="EMBL"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Sequence
            implements Serializable
        {

            private final static long serialVersionUID = -1L;
            @XmlAttribute(name = "resource", required = true)
            protected String resource;
            @XmlAttribute(name = "id", required = true)
            protected String id;
            @XmlAttribute(name = "version")
            protected Integer version;

            /**
             * Gets the value of the resource property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getResource() {
                return resource;
            }

            /**
             * Sets the value of the resource property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setResource(String value) {
                this.resource = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the version property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getVersion() {
                return version;
            }

            /**
             * Sets the value of the version property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setVersion(Integer value) {
                this.version = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="acronym" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="dbReference" type="{http://uniprot.org/uniprot}dbReferenceType"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "acronym",
        "description",
        "dbReference"
    })
    public static class Disease
        implements Serializable
    {

        private final static long serialVersionUID = -1L;
        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected String acronym;
        @XmlElement(required = true)
        protected String description;
        @XmlElement(required = true)
        protected DbReferenceType dbReference;
        @XmlAttribute(name = "id", required = true)
        protected String id;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the acronym property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAcronym() {
            return acronym;
        }

        /**
         * Sets the value of the acronym property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAcronym(String value) {
            this.acronym = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the dbReference property.
         * 
         * @return
         *     possible object is
         *     {@link DbReferenceType }
         *     
         */
        public DbReferenceType getDbReference() {
            return dbReference;
        }

        /**
         * Sets the value of the dbReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link DbReferenceType }
         *     
         */
        public void setDbReference(DbReferenceType value) {
            this.dbReference = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="KM" type="{http://uniprot.org/uniprot}evidencedStringType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="Vmax" type="{http://uniprot.org/uniprot}evidencedStringType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="text" type="{http://uniprot.org/uniprot}evidencedStringType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "kms",
        "vmaxes",
        "texts"
    })
    public static class Kinetics
        implements Serializable
    {

        private final static long serialVersionUID = -1L;
        @XmlElement(name = "KM")
        protected List<EvidencedStringType> kms;
        @XmlElement(name = "Vmax")
        protected List<EvidencedStringType> vmaxes;
        @XmlElement(name = "text")
        protected List<EvidencedStringType> texts;

        /**
         * Gets the value of the kms property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the kms property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getKMS().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EvidencedStringType }
         * 
         * 
         */
        public List<EvidencedStringType> getKMS() {
            if (kms == null) {
                kms = new ArrayList<EvidencedStringType>();
            }
            return this.kms;
        }

        /**
         * Gets the value of the vmaxes property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vmaxes property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVmaxes().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EvidencedStringType }
         * 
         * 
         */
        public List<EvidencedStringType> getVmaxes() {
            if (vmaxes == null) {
                vmaxes = new ArrayList<EvidencedStringType>();
            }
            return this.vmaxes;
        }

        /**
         * Gets the value of the texts property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the texts property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTexts().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EvidencedStringType }
         * 
         * 
         */
        public List<EvidencedStringType> getTexts() {
            if (texts == null) {
                texts = new ArrayList<EvidencedStringType>();
            }
            return this.texts;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Link
        implements Serializable
    {

        private final static long serialVersionUID = -1L;
        @XmlAttribute(name = "uri", required = true)
        @XmlSchemaType(name = "anyURI")
        protected String uri;

        /**
         * Gets the value of the uri property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUri() {
            return uri;
        }

        /**
         * Sets the value of the uri property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUri(String value) {
            this.uri = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="text" type="{http://uniprot.org/uniprot}evidencedStringType" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "texts"
    })
    public static class PhDependence
        implements Serializable
    {

        private final static long serialVersionUID = -1L;
        @XmlElement(name = "text", required = true)
        protected List<EvidencedStringType> texts;

        /**
         * Gets the value of the texts property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the texts property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTexts().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EvidencedStringType }
         * 
         * 
         */
        public List<EvidencedStringType> getTexts() {
            if (texts == null) {
                texts = new ArrayList<EvidencedStringType>();
            }
            return this.texts;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="text" type="{http://uniprot.org/uniprot}evidencedStringType" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "texts"
    })
    public static class RedoxPotential
        implements Serializable
    {

        private final static long serialVersionUID = -1L;
        @XmlElement(name = "text", required = true)
        protected List<EvidencedStringType> texts;

        /**
         * Gets the value of the texts property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the texts property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTexts().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EvidencedStringType }
         * 
         * 
         */
        public List<EvidencedStringType> getTexts() {
            if (texts == null) {
                texts = new ArrayList<EvidencedStringType>();
            }
            return this.texts;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="text" type="{http://uniprot.org/uniprot}evidencedStringType" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "texts"
    })
    public static class TemperatureDependence
        implements Serializable
    {

        private final static long serialVersionUID = -1L;
        @XmlElement(name = "text", required = true)
        protected List<EvidencedStringType> texts;

        /**
         * Gets the value of the texts property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the texts property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTexts().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EvidencedStringType }
         * 
         * 
         */
        public List<EvidencedStringType> getTexts() {
            if (texts == null) {
                texts = new ArrayList<EvidencedStringType>();
            }
            return this.texts;
        }

    }

}
