package org.batteryparkdev.cosmicgraphdb.poc

import com.google.common.flogger.FluentLogger
import org.uniprot.uniprot.Uniprot
import java.io.FileReader
import javax.xml.bind.JAXBContext

/*
Basic POC code to experiment with parsing UniProt XML using Java classes generated by the
JAXB xjc compiler
Validates that generate Java code can parse UniProt XML
 */

fun main() {
    val logger: FluentLogger = FluentLogger.forEnclosingClass();
    val  context = JAXBContext.newInstance(Uniprot::class.java)
    val uniprot = context.createUnmarshaller()
        .unmarshal(FileReader("./data/uniprot_sprot_human.xml"))
            as Uniprot
    uniprot.entries.stream().forEach {it ->
        it.names.stream().forEach { name -> println(name) }
        it.genes.stream().forEach { gene -> println(gene.names[0].value?: "NA") }
    }
    logger.atInfo().log("UniProt Entry count = ${uniprot.entries.size}")
}

